import json
import tempfile
import unittest
from pathlib import Path

from coprogrammer.cli import (
    build_pr_comment_body,
    classify_risks,
    load_pull_request_number,
    new_heartbeat,
    render_digest,
    resolve_language,
    validate_manifest,
)


class RiskClassificationTest(unittest.TestCase):
    def test_classifies_contract_and_security_paths(self) -> None:
        risks = classify_risks(
            [
                "schemas/change-manifest.schema.json",
                "src/auth/session.py",
                "README.md",
            ]
        )

        self.assertIn("contract", risks)
        self.assertIn("security", risks)
        self.assertNotIn("build", risks)


class LocalizationTest(unittest.TestCase):
    def test_resolves_chinese_alias(self) -> None:
        self.assertEqual(resolve_language("zh"), "zh-CN")

    def test_render_digest_in_chinese(self) -> None:
        digest = render_digest(
            "origin/main",
            "HEAD",
            [{"status": "A", "path": "schemas/api.json"}],
            ["abc123 Add API"],
            "zh-CN",
        )

        self.assertIn("# 分支消化报告", digest)
        self.assertIn("## 变更文件", digest)
        self.assertIn("**共享契约**", digest)


class ManifestValidationTest(unittest.TestCase):
    def test_accepts_minimal_valid_manifest(self) -> None:
        payload = {
            "task": "Add login API",
            "intent": "Allow users to sign in",
            "scope": "backend",
            "core_changes": [],
            "contracts": [],
            "tests": [],
            "risks": [],
        }
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "manifest.json"
            path.write_text(json.dumps(payload), encoding="utf-8")

            ok, errors = validate_manifest(path)

        self.assertTrue(ok)
        self.assertEqual(errors, [])

    def test_rejects_missing_required_fields(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "manifest.json"
            path.write_text("{}", encoding="utf-8")

            ok, errors = validate_manifest(path)

        self.assertFalse(ok)
        self.assertIn("missing required field: task", errors)


class HeartbeatTest(unittest.TestCase):
    def test_new_heartbeat_shape(self) -> None:
        heartbeat = new_heartbeat("agent-a", "Implement digest")

        self.assertEqual(heartbeat["agent"], "agent-a")
        self.assertEqual(heartbeat["status"], "working")
        self.assertEqual(heartbeat["currently_editing"], [])


class GitHubCommentTest(unittest.TestCase):
    def test_build_pr_comment_body_includes_marker_and_digest(self) -> None:
        body = build_pr_comment_body("# Branch Digest\n\ncontent", "<!-- marker -->")

        self.assertIn("<!-- marker -->", body)
        self.assertIn("# Branch Digest", body)
        self.assertIn("Generated by CoProgrammer", body)

    def test_build_pr_comment_body_truncates_large_digest(self) -> None:
        body = build_pr_comment_body("x" * 70000)

        self.assertLessEqual(len(body), 65000)
        self.assertIn("truncated", body)

    def test_build_pr_comment_body_in_chinese(self) -> None:
        body = build_pr_comment_body("# 分支消化报告", language="zh-CN")

        self.assertIn("CoProgrammer 分支消化报告", body)
        self.assertIn("由 CoProgrammer 生成", body)

    def test_load_pull_request_number(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "event.json"
            path.write_text(
                json.dumps({"pull_request": {"number": 42}}),
                encoding="utf-8",
            )

            number = load_pull_request_number(path)

        self.assertEqual(number, 42)


if __name__ == "__main__":
    unittest.main()
